exports.HTTP_CODES = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  PRECONDITION_FAILED: 412,
  REQUEST_FAILED: 422,
  INTERNAL_SERVER_ERROR: 500,
};

exports.Errors = {
  USER_EXISTS: "USR-404",
  NOT_FOUND: "NOT-FOUND",
  USER_INVALID: "USER NOT FOUND",
};
